export const RESEARCH_SOURCES = [
  {
    name: "SAM registration",
    group: "Identity & eligibility",
    url: "https://sam.gov/search/?index=entity",
    access: "Official search",
    note: "Confirm the exact UEI, registration status, and purpose of registration.",
  },
  {
    name: "SAM exclusions",
    group: "Identity & eligibility",
    url: "https://sam.gov/search/?index=ex",
    access: "Official search",
    note: "Check exact identifiers. No automated exclusion determination is made here.",
  },
  {
    name: "Consolidated Screening List",
    group: "Identity & eligibility",
    url: "https://www.trade.gov/consolidated-screening-list",
    access: "Official search / keyed API",
    note: "Potential restricted-party matches require identity and restriction review.",
  },
  {
    name: "DLA CAGE / NCAGE",
    group: "Identity & eligibility",
    url: "https://cage.dla.mil/",
    access: "Official search",
    note: "Additional entity and facility identifiers; registration does not establish access.",
  },
  {
    name: "GLEIF legal entities",
    group: "Identity & eligibility",
    url: "https://search.gleif.org/",
    access: "Live name lookup",
    note: "Use the supplier panel to retrieve possible LEI matches. No automatic name-based merge.",
  },
  {
    name: "Etimad tenders",
    group: "Host-government procurement",
    countries: ["SAU"],
    url: "https://tenders.etimad.sa/",
    access: "Official portal",
    note: "Saudi public tender and award research. Supplier-level open API coverage has not been verified.",
  },
  {
    name: "Etimad Open Data API",
    group: "Host-government procurement",
    countries: ["SAU"],
    url: "https://portal.etimad.sa/getattachment/7b1b7823-1fe8-41bb-8b07-334ce5306ce8/opendata-api-igOpenData-API-IG.pdf?disposition=attachment",
    access: "Documented / not connected",
    note: "Production endpoint, dataset identifiers, and named-supplier coverage need validation.",
  },
  {
    name: "EU Tenders Electronic Daily",
    group: "Other public buyers",
    url: "https://ted.europa.eu/",
    access: "Official search / public API",
    note: "Contract and award notices across covered European procurement. Not ingested in this version.",
  },
  {
    name: "UK Find a Tender",
    group: "Other public buyers",
    url: "https://www.find-tender.service.gov.uk/Search",
    access: "Official search / public API",
    note: "Published UK procurement notices and awards. Not ingested in this version.",
  },
  {
    name: "World Bank contract awards",
    group: "Other public buyers",
    url: "https://financesone.worldbank.org/d/DS00005",
    access: "Public dataset / API",
    note: "Investment-project contract awards, with supplier and borrower countries. Not ingested in this version.",
  },
  {
    name: "Open Contracting Data Registry",
    group: "Host-government procurement",
    url: "https://data.open-contracting.org/en/search/",
    access: "Source discovery",
    note: "Find country procurement publishers; coverage, licensing, and update frequency vary.",
  },
  {
    name: "SAM opportunities & sources sought",
    group: "Demand & competition",
    url: "https://sam.gov/search/?index=opp",
    access: "Official search",
    note: "Research specifications, public notices, and upcoming requirements.",
  },
  {
    name: "USAspending source disclosures",
    group: "Coverage & methodology",
    url: "https://www.usaspending.gov/data/about-the-data-download.pdf",
    access: "Methodology",
    note: "Review reporting thresholds, delays, duplicates, and other source limitations.",
  },
];
