// Access descriptions are deliberately separate from live source availability.
export const SOURCES = [
  {
    id: "awards",
    name: "Federal award history",
    provider: "USAspending",
    group: "Buying history",
    modes: ["requirement", "supplier"],
    direct: true,
    url: "https://www.usaspending.gov/search",
    scope:
      "Contract awards matching USAspending’s date-window filter; performance dates can extend beyond this window. keyword or recipient, NAICS, PSC, and U.S. performance-state filters. First 50 results per page, newest start dates first. Award amounts are not unit prices.",
  },
  {
    id: "small-business",
    name: "Small-business award history",
    provider: "USAspending",
    group: "Suppliers",
    modes: ["requirement", "supplier"],
    direct: true,
    url: "https://www.usaspending.gov/search",
    scope:
      "Historical awards tagged small business. Same filters as award history; performance dates can extend beyond the search window. This does not establish current certification, capability, competitive pricing, or a rule-of-two determination.",
  },
  {
    id: "vehicles",
    name: "Contract vehicle history",
    provider: "USAspending",
    group: "Vehicles",
    modes: ["requirement", "supplier"],
    direct: true,
    url: "https://www.usaspending.gov/search",
    scope:
      "IDIQ, BPA, and other IDV records matching USAspending’s date-window filter; ordering periods can extend beyond the search window. Verify scope, ordering eligibility, capacity, and ordering period with the managing agency.",
  },
  {
    id: "opportunities",
    name: "Opportunities & sources sought",
    provider: "SAM.gov",
    group: "Buying history",
    modes: ["requirement"],
    url: "https://sam.gov/search/?index=opp",
    scope:
      "Title, NAICS, and PSC search. Posted dates are limited to the most recent 360 days within your selected window. Notices may include closed deadlines. Performance-state filter is not applied.",
  },
  {
    id: "calc",
    name: "Labor ceiling rates",
    provider: "GSA CALC+",
    group: "Pricing",
    modes: ["requirement", "supplier"],
    direct: true,
    url: "https://buy.gsa.gov/pricing/qr/ceiling-rates",
    scope:
      "Keyword across labor category, vendor, and contract number. Up to 50 rows per page, category order. Ceiling rates are not prices paid or wage rates. Brief location, dates, NAICS, and PSC are not filters here.",
  },
  {
    id: "entities",
    name: "Registered supplier lookup",
    provider: "SAM.gov",
    group: "Suppliers",
    modes: ["supplier"],
    url: "https://sam.gov/search/?index=entity",
    scope:
      "Legal business name lookup for active SAM registrations. Confirm the exact UEI/CAGE and current status in SAM before relying on a match.",
  },
  {
    id: "exclusions",
    name: "Federal exclusion lookup",
    provider: "SAM.gov",
    group: "Suppliers",
    modes: ["supplier"],
    url: "https://sam.gov/search/?index=ex",
    scope:
      "Name-based screening only. A name match is not confirmed identity, and no matches is not an eligibility clearance. Check exact identifiers in the official record.",
  },
  {
    id: "gleif",
    name: "Legal entity & ownership leads",
    provider: "GLEIF",
    group: "Suppliers",
    modes: ["supplier"],
    direct: true,
    url: "https://search.gleif.org/",
    scope:
      "Full-text legal entity records worldwide. LEI coverage is incomplete; similar names and subsidiaries need identity checks.",
  },
  {
    id: "regulations",
    name: "Regulations & notices",
    provider: "Federal Register",
    group: "Market context",
    modes: ["requirement", "supplier"],
    direct: true,
    url: "https://www.federalregister.gov/documents/search",
    scope:
      "Keyword relevance search within your date window. Notices are context; review the actual applicability and effective date.",
  },
  {
    id: "nih",
    name: "Research & innovation projects",
    provider: "NIH RePORTER",
    group: "Innovation",
    modes: ["requirement"],
    direct: true,
    url: "https://reporter.nih.gov/",
    scope:
      "Text search across research projects. Not restricted to your award window or NAICS. Research funding is an innovation lead, not evidence of commercial readiness.",
  },
  {
    id: "bls",
    direct: true,
    name: "Consumer price index context",
    provider: "BLS",
    group: "Pricing",
    modes: ["requirement", "supplier"],
    url: "https://data.bls.gov/timeseries/CUUR0000SA0",
    scope:
      "National CPI-U all items, not seasonally adjusted; latest available observations. General context only, not a category-specific escalation factor or supplier price.",
  },
  {
    id: "news",
    name: "Recent market news",
    provider: "NewsAPI",
    group: "Market context",
    modes: ["requirement", "supplier"],
    url: "https://news.google.com/",
    scope:
      "Recent keyword news from the existing connection. Coverage and publisher dates vary. Articles are leads and may be unrelated or behind paywalls.",
  },
  {
    id: "patents",
    name: "Patent leads",
    provider: "PatentsView",
    group: "Innovation",
    modes: ["requirement", "supplier"],
    optional: true,
    url: "https://search.patentsview.org/",
    scope:
      "Requires a separately connected PatentsView key. Patent records do not establish product availability, freedom to operate, or ownership rights today.",
  },
  {
    id: "corporations",
    name: "Corporate registry records",
    provider: "OpenCorporates",
    group: "Suppliers",
    modes: ["supplier"],
    optional: true,
    url: "https://opencorporates.com/",
    scope:
      "Optional licensed connection. Verify jurisdiction and exact legal entity; registry presence does not demonstrate capability.",
  },
  {
    id: "web",
    name: "Commercial web discovery",
    provider: "Brave Search",
    group: "Commercial market",
    modes: ["requirement", "supplier"],
    optional: true,
    url: "https://search.brave.com/",
    scope:
      "Optional search connection for manufacturers, product pages, distributors, and service providers. Snippets are discovery leads; open the original page and verify specifications, price basis, and dates.",
  },
];

export const LIBRARY = [
  [
    "sam",
    "SAM.gov",
    "Suppliers",
    "Public / sign-in",
    "https://sam.gov/",
    "Registration, opportunities, exclusions, contract data, and wage determinations. Use exact UEI or CAGE when validating a firm.",
  ],
  [
    "sba",
    "SBA Small Business Search",
    "Suppliers",
    "Public search",
    "https://search.certifications.sba.gov/",
    "Find capability narratives and small-business certification records. Confirm currency and relevance to the requirement.",
  ],
  [
    "cage",
    "DLA CAGE Search",
    "Suppliers",
    "Official portal",
    "https://cage.dla.mil/",
    "Resolve CAGE/NCAGE identity and facility records.",
  ],
  [
    "apex",
    "APEX Accelerators",
    "Suppliers",
    "Assisted research",
    "https://www.apexaccelerators.us/",
    "Find regional help identifying small businesses and nontraditional suppliers.",
  ],
  [
    "lynx",
    "LYNX",
    "Suppliers",
    "Account may be required",
    "https://www.lynxconnect.io/",
    "Supplier capabilities and industrial-base connections.",
  ],
  [
    "mep",
    "NIST MEP Supplier Scouting",
    "Suppliers",
    "Assisted research",
    "https://www.nist.gov/mep/supply-chain/supplier-scouting",
    "Identify potential domestic manufacturers with MEP centers.",
  ],
  [
    "thomas",
    "Thomasnet",
    "Commercial market",
    "Commercial portal",
    "https://www.thomasnet.com/",
    "Industrial manufacturers, distributors, capabilities, and product categories.",
  ],
  [
    "advantage",
    "GSA Advantage!",
    "Commercial market",
    "Catalog / account for purchase",
    "https://www.gsaadvantage.gov/",
    "Product models, catalog terms, and listed prices. Capture unit, quantity, freight, and quote date.",
  ],
  [
    "fedmall",
    "FedMall",
    "Commercial market",
    "PIEE account / authorized access",
    "https://www.dla.mil/Info/FedMall/",
    "Government and commercial catalogs, pricing, and DLA inventory.",
  ],
  [
    "dibbs",
    "DLA DIBBS",
    "Commercial market",
    "Official portal",
    "https://www.dibbs.bsm.dla.mil/",
    "Supply solicitations and award information for part-number and NSN research.",
  ],
  [
    "abilityone",
    "AbilityOne Procurement List",
    "Required-source research",
    "Public search",
    "https://www.abilityone.gov/procurement_list/",
    "Check the official Procurement List and the scope of any listed requirement.",
  ],
  [
    "unicor",
    "UNICOR / Federal Prison Industries",
    "Required-source research",
    "Public catalog",
    "https://www.unicor.gov/",
    "Research available products and services and applicable purchasing procedures.",
  ],
  [
    "elibrary",
    "GSA eLibrary",
    "Vehicles",
    "Public search",
    "https://www.gsaelibrary.gsa.gov/",
    "Contract holders, SINs, contract terms, and price-list links.",
  ],
  [
    "copilot",
    "Procurement Co-Pilot",
    "Buying history",
    "Official portal",
    "https://acquisitiongateway.gov/procurementcopilot",
    "Research pricing, contracts, and suppliers across government buying data.",
  ],
  [
    "gateway",
    "Acquisition Gateway",
    "Vehicles",
    "Public / sign-in",
    "https://acquisitiongateway.gov/",
    "Acquisition resources, contract vehicles, forecasts, and planning tools.",
  ],
  [
    "calc-library",
    "GSA Pricing Intelligence Suite",
    "Pricing",
    "Public / restricted tools",
    "https://buy.gsa.gov/pricing/",
    "CALC+ ceilings, BLS wage tools, IGCE tools, and restricted prices-paid research.",
  ],
  [
    "mras",
    "GSA Market Research as a Service",
    "Engagement",
    "Government service",
    "https://www.gsa.gov/mras",
    "Request assisted research, RFIs, and supplier engagement.",
  ],
  [
    "oasis",
    "OASIS+",
    "Vehicles",
    "Official program guidance",
    "https://www.gsa.gov/oasis-plus",
    "Research services scope, eligible users, contract holders, and ordering procedures.",
  ],
  [
    "bmo",
    "Building Maintenance & Operations",
    "Vehicles",
    "Official program guidance",
    "https://www.gsa.gov/bmo",
    "Facilities-services vehicles and research resources.",
  ],
  [
    "eda",
    "Electronic Data Access / PIEE",
    "Buying history",
    "Authorized government access",
    "https://piee.eb.mil/",
    "Original contract documents, terms, and pricing. Keep restricted records in approved systems.",
  ],
  [
    "cpars",
    "CPARS",
    "Suppliers",
    "Authorized access",
    "https://www.cpars.gov/",
    "Past-performance information for authorized users. Public award history is not a substitute.",
  ],
  [
    "bls-library",
    "BLS Data & Occupational Outlook",
    "Pricing",
    "Public data",
    "https://www.bls.gov/data/",
    "Labor markets, wages, inflation, and industry series. Select an appropriate occupation and geography.",
  ],
  [
    "ooh",
    "Occupational Outlook Handbook",
    "Pricing",
    "Public data",
    "https://www.bls.gov/ooh/",
    "Occupation definitions, labor outlook, and compensation context.",
  ],
  [
    "bea",
    "Bureau of Economic Analysis",
    "Market context",
    "Public data",
    "https://www.bea.gov/",
    "Industry output, regional activity, and broader economic context.",
  ],
  [
    "census",
    "Census NAICS",
    "Market context",
    "Public reference",
    "https://www.census.gov/naics/",
    "Official NAICS definitions and classification references.",
  ],
  [
    "size",
    "SBA Size Standards",
    "Suppliers",
    "Public reference",
    "https://www.sba.gov/document/support-table-size-standards",
    "Current size-standard tables and related guidance; select the correct industry and exceptions.",
  ],
  [
    "sec",
    "SEC EDGAR",
    "Suppliers",
    "Public filings",
    "https://www.sec.gov/search-filings",
    "Company filings, financial condition, business segments, and reported risks.",
  ],
  [
    "commerce",
    "Commerce Company & Industry Research",
    "Market context",
    "Research library",
    "https://library.doc.gov/company/market",
    "Industry reports, company research methods, and economic statistics.",
  ],
  [
    "ita",
    "International Trade Administration",
    "Market context",
    "Public research",
    "https://www.trade.gov/market-intelligence",
    "Country, industry, trade, and export-market intelligence.",
  ],
  [
    "datagov",
    "Data.gov",
    "Market context",
    "Public catalog",
    "https://data.gov/",
    "Find specialized federal datasets and their original publishing agencies.",
  ],
  [
    "sbir",
    "SBIR/STTR Awards",
    "Innovation",
    "Public search; API maintenance",
    "https://www.sbir.gov/awards",
    "Find small-business research performers. The API documentation currently reports maintenance; use the official award search.",
  ],
  [
    "nsf",
    "NSF Award Search",
    "Innovation",
    "Public search",
    "https://www.nsf.gov/awardsearch/",
    "Find funded research, investigators, organizations, and technology leads.",
  ],
  [
    "techport",
    "NASA TechPort",
    "Innovation",
    "Public search",
    "https://techport.nasa.gov/",
    "Research NASA technology projects and development activity.",
  ],
  [
    "diu",
    "Defense Innovation Unit",
    "Innovation",
    "Public portal",
    "https://www.diu.mil/",
    "Commercial technology focus areas and innovation opportunities.",
  ],
  [
    "patentsearch",
    "USPTO Patent Public Search",
    "Innovation",
    "Public search",
    "https://ppubs.uspto.gov/pubwebapp/",
    "Search original patents and applications; investigate IP questions with appropriate specialists.",
  ],
  [
    "fedramp",
    "FedRAMP Marketplace",
    "Commercial market",
    "Public directory",
    "https://marketplace.fedramp.gov/",
    "Verify a cloud offering’s specific authorization status and boundary in the official record.",
  ],
  [
    "dcma",
    "DCMA Commercial Item Group",
    "Market context",
    "Official resource",
    "https://www.dcma.mil/Commercial-Item-Group/",
    "Commerciality and pricing resources and assistance.",
  ],
  [
    "pil",
    "DHS Procurement Innovation Lab",
    "Engagement",
    "Public resources",
    "https://www.dhs.gov/pil",
    "Industry engagement and acquisition technique resources.",
  ],
  [
    "compass",
    "DAF Contracting Compass",
    "Market context",
    "Authorized SharePoint access",
    "https://usaf.dps.mil/sites/AFCC/AQCP/KnowledgeCenter/SitePages/DAF-Contracting-Compass/Part-10---Market-Research.aspx",
    "Department-specific guidance and resources.",
  ],
  [
    "pam",
    "Army Procurement Portal",
    "Market context",
    "Authorized SharePoint access",
    "https://armyeitaas.sharepoint-mil.us/sites/ASA-ALT-PAMProcProc/SitePages/Market_Research.aspx",
    "Army market-research guidance and tools.",
  ],
  [
    "genai",
    "GenAI.mil",
    "Analysis",
    "Authorized government environment",
    "https://genai.mil/",
    "Use your approved environment to synthesize validated research. Confirm authorization for the data you plan to provide.",
  ],
  [
    "turbo",
    "TurboInnovate Government",
    "Innovation",
    "Government account",
    "https://cdao.turboinnovate.com/",
    "Technology, vendor, and market-research tools for authorized government users.",
  ],
].map(([id, name, group, access, url, description]) => ({
  id,
  name,
  group,
  access,
  url,
  description,
}));

export const SOURCE_MAP = Object.freeze(
  Object.assign(
    Object.create(null),
    Object.fromEntries(SOURCES.map((s) => [s.id, s])),
  ),
);
export const LEGACY_ROUTES = {
  opportunities: "/search/opps",
  entities: "/entity/sam",
  exclusions: "/entity/sanctions",
  news: "/search/news",
  patents: "/search/patents",
  corporations: "/entity/oc",
};
